name: training
publish_to: none
description: A package that be used in yumemi-inc/flutter-training for getting pseudo weather forecast.
version: 1.0.0
homepage: https://github.com/yumemi-inc/flutter-training/tree/main/packages/yumemi_weather

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.6
  provider: ^6.0.0

  yumemi_weather:
    git:
      url: https://github.com/yumemi-inc/flutter-training.git
      ref: main
      path: packages/yumemi_weather

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0

flutter:
   uses-material-design: true