name: training
publish_to: none
description: A package that be used in yumemi-inc/flutter-training for getting pseudo weather forecast.
version: 1.0.0
homepage: https://github.com/yumemi-inc/flutter-training/tree/main/packages/yumemi_weather

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  provider: ^6.0.0
  riverpod: ^2.1.3

  yumemi_weather:
    git:
      url: https://github.com/yumemi-inc/flutter-training.git
      ref: main
      path: packages/yumemi_weather
  

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  lints: ^2.0.1
  test: ^1.22.0

flutter:
  assets:
    - docs/sessions/images/api/
  uses-material-design: true